### PR TITLE
Ported 12.04 LTS Script

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Updated Dependency Checks tested on DigitalOcean x64 12.10 & x32 12.10 after running 
    apt-get update and apt-get upgrade

  #postfix install on 12.10
  aptitude remove exim4 && aptitude install postfix && postfix stop

### CODE REVIEW

**Comment by allebb** [comment]
Thanks for your PR however, adding your name at the top of the existing installation script as the script 'Author' takes the piss a bit lol given that myself and the rest of the team pretty much did all of the script minus your new  'aptitude remove exim4 && aptitude install postfix && postfix stop' line!! - Also, this script as per your PR description states this caters for DigitalOcean users, I'd recommend that you add checks to first see if exim4 and postfix is actually installed before attempting to delete it as these scripts MUST also work with standard 'FRESH' installs of Ubuntu etc. eg. try 'which exim4' to see if that returns a value and if so then remove it.

Closing this PR for the above reasons.

**Comment by Lewiscowles1986** [comment]
Hi Bob so glad reading is high on your list of abilities wonder how you missed "Lewis Cowles (CODESIGN2, Minor Modification of existing 12.04 LTS script)" Which does state it is a modification of the existing script which is for a bloody old Ubuntu (2 years old on 26 April 2012).

Furthermore it is only tested on digitalocean does not mean it will only work there, it means I dont have infinite time, which is why I did something quick. It also works on stock 12.10 for users who simply click next a lot (just tested in a VM) and linode 12.10 stock... Have you tested it and it failed, that would be great feedback but test more just makes you come off as a complete dick!

Im not going to try creating another pull request but consider the ageing state of your repo with 4 months of simply "#here béta ubuntu 12.10" I thought some of your users might appreciate a quick 2 min mod of the 12.04 script so they could muddle ahead hence the title "Ported 12.04 LTS Script"

**Comment by allebb** [comment]
The script is NOT two years old, the version of Ubuntu that it is designed
for was release two years ago however and the reason for this is because we
only officially support the LTS versions of Ubuntu. At present Ubunutu
12.04 LTS is still patched and is the RECOMMENDED version for commercial
installations so your argument really is a little flawed there!

I've not tested it as I see no point, why would we 'merge' something into
our official repository when A) We don't officially support non-LTS release
(in this case 12.10) and B) It would appear that the fact that Postfix is
already installed is due to a ISP custom VM image, this kind of 'quick fix'
should be discussed/provided in the forums not as a separate script that
would just confuse people when installing on a certain ISP's platform.

...anyway based on your response you probably don't even care about my
reply here and I didn't mean to come across as a 'cunt' although thanks for
pointing that out!

Cheers,
Bobby

**Comment by Lewiscowles1986** [comment]
Actually thanks for the reply, I did edit my comment as I thought my own language was a bit strong, it was late, drink was involved I read swearing, I responded with swearing, apologies for my part in the swearing, but if you do not plan to have 12.10 can you please remove the placeholder script you obviously let through so that people wanting to use your software on more modern platforms "get it" that platform get that you don't want them to. on the LTS, I know what an LTS is, it is not the only business ready solution, but I get that some businesses would only feel comfortable with an LTS release. With this in mind 13.04 LTS has been out for over a year and I do also have 13.04 and 13.10 alas only tested on my own pc and digitalocean, so I wont be contributing them here, maybe I'll blog them, maybe I'll delete them, I honestly was not trying to pass off others works as my own I just wanted to submit something I had used for a client who seemed to need zpanelX...

**Comment by TheNigelist** [comment]
Funny how you say 13.04 LTS?? Ubuntu releases it's LTS versions every 2 years and the next LTS release is this month (14.04). 

The 12.10 script is the beta part of the repo for the reason that it hasn't been officially tested, but you can just upgrade to 12.10  using
`sudo apt-get do-release-upgrade`
But I wouldn't recommend going past there, you'll also need the suhosin fix from the forums.

**Comment by TheNigelist** [comment]
Sorry it's 

`sudo do-release-upgrade`

**Pull request closed without merging**
