### PR TITLE
Updater add check zpanel version

### PR DESCRIPTION
**Pull request by andykimpe**
add check zpanel version on Updater

### CODE REVIEW

**Comment by andykimpe** [comment]
any improvement to avoid compatibility issue

**Comment by andykimpe** [comment]
add kickstart installer CentOS 5 béta

test 100% work

**Comment by allebb** [comment]
Thanks for the pull request, I like the idea of using tzdata to prompt for timezone info etc. but I just wanted to ask though... how come you've changed the 'curl -s' to 'wget -qO'? - Is there a reason why you prefer this? - By default most sites use curl?? - eg. http://getcomposer.org/download/

**Comment by andykimpe** [comment]
yes curl is not installed by default, while wget and install by default on most server

**Comment by allebb** [comment]
haha... that is the other way around on Ubuntu Server (my main and preferred server distro), obviously CentOS is different then ;) By default Ubuntun Server has curl installed and not wget!

**Comment by andykimpe** [comment]
default not there are not installed but as he and very use most of the host the default install

**Comment by allebb** [comment]
Huh lol?? - I don't know what you mean? lol - Write it in French and then
use Google Translate ;) - I  can confirm that my Ubuntu 12.04 LTS server(s)
have cURL installed by default though :) - I guess as the installers
install wget its probably a good idea to use wget instead anyways as
regardless of whether the distro has wget installed or not it will be
installed by the installer anyway.

**Pull request merged**
