### PR TITLE
Update 10_1_1.sh

### PR DESCRIPTION
**Pull request by ghost**
Enable PHP error logs as default in centos.
Could help a lot in support & users fixing issues. 
Will check for ubuntu to apply it and add it to upgrade scripts too.

Me.B

### CODE REVIEW

**Comment by allebb** [comment]
I disagree, this is not something that should NOT be  'default' for production servers, I'm going to close this request as in my opinion would add additional IO and disk space usage when 95% of the time this wouldn't be needed (just unnecessary).

**Comment by lottfy** [comment]
Good to to enable it e.g 10.1.1dev.sh so help tester's to detect more errors to fix it

**Comment by ghost** [comment]
OR we could set a question asking if we would like to enable extended dev features. 

And keep default to not install. So any one can choose to deploy this or not.

Like we could offer to enable or not firewall with default set of ports open / rules.

M B

**Comment by lottfy** [comment]
good to have 2 files default for normal user's and other to Dev  plus good to add to dev .sh ability to know code tag "This feature asked Caff to add it "
never mind to write simple script so after install 10.1.1.sh apply this script "Dev.script"

**Pull request closed without merging**
