### PR TITLE
Fixed missing db.php insert and mysql service name

### PR DESCRIPTION
**Pull request by stokes84**
Installer was missing 
`sed -i "s|YOUR_ROOT_MYSQL_PASSWORD|$password|" /etc/zpanel/panel/cnf/db.php`
Also mysql service was referenced as mysqld service. 
Fixes issue #13

Also fixing "Cron Task" permission issue on contabs folder. Cron Tasks can now be created.

### CODE REVIEW

**Comment by stokes84** [comment]
Haven't tested if Cron Task creation works in versions previous to 10.1.1 to know if `chmod 744 /var/spool/cron/crontabs` is needed for the update script. Maybe someone running an older version can test? Otherwise once this gets pulled I'll make it checkout to a later version to test that.

**Comment by trojanspike** [comment]
Have you tried this in a VM?

**Comment by stokes84** [comment]
Yep, if by VM you imply a VPS qualifies. I do most testing in a VPS, can wipe, reload or switch OS, and have it booted up in a matter of seconds.

**Comment by trojanspike** [comment]
Sweet :+1:

**Comment by stokes84** [comment]
Feel free to test just replace the installer link with the one from my fork

**Comment by stokes84** [comment]
Example
`bash <(curl -Ss https://raw.github.com/stokes84/installers/master/install/Ubuntu-12_04/10_1_1.sh)`

**Comment by stokes84** [comment]
That was odd, was editing this from the work VPN and somehow it bugged out on a comment click and got closed lol? Maybe someone over here messing with me. Anyways, had to reopen, it's back in pull requests.

**Comment by allebb** [comment]
Merged! :)

**Pull request closed without merging**
